# Generated by Django 3.2 on 2021-04-23 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('wheelchair', models.BooleanField(default=False)),
                ('goal_time', models.DurationField()),
                ('real_time', models.DurationField()),
                ('dob', models.DateField()),
                ('sex', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort', models.PositiveIntegerField()),
                ('race_year', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='mercury_api.race')),
                ('runner_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='mercury_api.runner')),
            ],
        ),
    ]
