# Generated by Django 3.2 on 2021-04-24 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercury_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='cohort',
            new_name='cohort_id',
        ),
        migrations.AlterField(
            model_name='result',
            name='race_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='race', to='mercury_api.race'),
        ),
        migrations.AlterField(
            model_name='result',
            name='runner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='runners', to='mercury_api.runner'),
        ),
    ]
