# Generated by Django 3.2 on 2021-04-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercury_api', '0005_auto_20210425_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='real_time',
            field=models.DurationField(null=True),
        ),
    ]
