# Generated by Django 3.2 on 2021-04-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercury_api', '0006_alter_runner_real_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runner',
            name='goal_time',
        ),
    ]
