# Generated by Django 3.2 on 2021-04-26 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercury_api', '0007_remove_runner_goal_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='cohort_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='runner',
            name='race_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='runners', to='mercury_api.race'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
